### PR TITLE
 Merge v1.18 from main

### PR DESCRIPTION
**Pull request by tresf**
Brings over 1.18 changes into the custom lmms branch.

Supersedes #2.

For a detailed breakdown of changes, see #1

Note, #1 has a lot of unnecessary whitespace changes, particularly `\r` `\n` changes.  These can be squashed out with a `.gitattributes` file as described here: https://stackoverflow.com/a/26490990/3196753.  This should be decided before merging (we can force-push these to `main` and then rebase this pull request).

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
How are we proceeding here? The code looks like it would not break parameters from old save files, and aside from that, I assume that the author themselves reviewed their code.

So maybe just a bit of testing? Should that be enough?

**Comment by tresf** [comment]
> So maybe just a bit of testing? Should that be enough?

Yes, I think so.

I had promised Richard Furse to send him some tests specifically in regards to Freeverb and sample rate changes, but never got around to it.

Quoting:

> **:left_speech_bubble: Richard**:  I don’t think I ever pushed this out onto the website… Did you have a chance to take a look at it?

***

> **:left_speech_bubble: Tres**:   I had promised to do some more comprehensive testing with the Freeverb plugin (and the email remains in my inbox and todo list) but I have not dedicated any time to this as I had initially promised, I'm very sorry.
> 
> I asked other (more DSP-savvy) developers for input, but none answered.
> 
> I still plan to eventually run this through some more tests to give some feedback on how it sounds at various bitrates.

***

> **:left_speech_bubble: Tres**:   I just wanted to send a thank you for adding freeverb sample rate changes to 1.18.  :)

**Comment by tresf** [comment]
For clarification, we already had these sample rate changes in our fork.  v1.18 upstreams them.

**Comment by JohannesLorenz** [comment]
OK. Then I guess that you don't need to be a DSP expert to test the changes?

**Comment by tresf** [comment]
> OK. Then I guess that you don't need to be a DSP expert to test the changes?

I would agree.

**Comment by JohannesLorenz** [comment]
OK. Then testing this would be most easy in https://github.com/LMMS/lmms/pull/6151 (which has no build yet), correct?

**Comment by tresf** [comment]
Pinging @Rossmaxx for possible help testing, since he's working on MSVC support here: #4

**Comment by Rossmaxx** [comment]
tested this branch, fix confirmed. LGTM.

**Comment by tresf** [comment]
Merging based on @Rossmaxx's testing.

**Pull request merged**
